### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by MrTFarnborough** [petetheman79/dailybibleverse-plugin#3]
I am sorry for asking such a noddy question, but I cannot workout how to install this plugin.

I have a multisite Wordpress setup. I have copied the verseoftheday-plugin.php into the plugin folder. I have tried putting it into folder called verseoftheday, I have tried zipping the file and then uploading it through Wordpress. All with no joy.

Thanks

Simon

**Comment by petetheman79** [comment]
Hi Simon, 

I have added a Release zip in the Releases folder & updated the README.md to include installation instructions.  Upload the zip in the release folder. Then configure the plugin.  

Let me know if that works for you? I used a single site install. If not I'll test it on a multi-site install.

Kind regards,
Peter

**Comment by MrTFarnborough** [comment]
Brilliant, it works on a multisite.

Are you able to select the bible version?

and can you turn off the image?

many thanks

**Comment by petetheman79** [comment]
Not yet. I will need to implement those features. Give me a couple of days
and I can work on them.

**Comment by petetheman79** [comment]
Hi Simon,

The new version is ready.

Kind regards,
Peter

**Comment by MrTFarnborough** [comment]
Excellent! Thanks.

On your other post you said the Admin could configure which version to use, does that mean we can add more versions or are we restricted to the 4 versions. We would normally use NIV.

Thanks

**Comment by MrTFarnborough** [comment]
Sorry should have said NIVUK

**Comment by petetheman79** [comment]
Unfortunately the ones that are listed are the only ones available. It's a
restriction for YouVersion as they do not have licenses for the other
versions.

I know that have been working with the other publishers to make it happen.
But doesnt look like its happened yet. I could ping them and see if I can
get more info.

**Comment by petetheman79** [comment]
By the way, how did you find my plugin?
